site:
  title: DrakonJsLocal Project Book
  url: /docs

content:
  sources:
    - url: .
      branches: main
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./public


