site:
  title: DSA Drakon JS
  start_page: drakon-js-docs::ROOT/index.html # Изменено здесь

content:
  sources:
    - url: https://github.com/ISA-1941/DrakonJs-Docs.git
      branches: [main]
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./public
