site:
  title: DSA Drakon JS
  start_page: drakon-js-docs::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: modules/ROOT
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./public
