site:
  title: Drakon.js Docs
  url: https://ISA-1941.github.io/DrakonJs-Docs/
content:
  sources:
    - url: ./docs-src
      branches: [HEAD]
ui:
  bundle:
    url: ./.ui/ui-bundle.zip
output:
  dir: ./docs