site:
  title: DRAKON JavaScript Docs
  url: https://ISA-1941.github.io/DrakonJs-Docs/
  start_page: drakonjs-docs::index.adoc

content:
  sources:
    - url: .
      branches: main
      start_path: docs-src

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./public
  clean: true
