site:
  title: DRAKON JavaScript Docs
  # Для локальной отладки URL можно оставить таким или изменить на localhost
  url: https://ISA-1941.github.io/DrakonJs-Docs/
  start_page: drakonjs-docs::index.adoc

content:
  sources:
    - url: .git
      branches: design-reset
      start_path: docs-src

asciidoc:
  attributes:
    lang: en

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # snapshot: true заставляет Antora обновлять UI при каждом запуске [4]
    snapshot: true
  # Если вы правите стили в папке supplemental-ui, эта строка очень важна [1, 5]
  supplemental_files: ./supplemental-ui

output:
  # Можно оставить public или изменить на build/site для ясности [6]
  dir: ./build/site
  clean: true

runtime:
  # Всегда проверять обновления в вашей локальной ветке [4, 7]
  fetch: true 


